### PR TITLE
Rename API key flag to client ID

### PR DESCRIPTION
**Pull request by gonzaloriestra**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/internal-cli-foundations/issues/547

### WHAT is this pull request doing?

- Hides `api-key` flag for all the commands
- Adds `client-id` flag for all the commands that used `api-key`
- Renames other `API key` references (only external) to `Client ID`, like errors
- Shows a warning when `api-key` flag is used notifying about the deprecation
20-45-slc8t-urdc4

### How to test your changes?

- `p shopify app dev --api-key whatever`
- `p shopify app dev --client-id whatever`
- Same for all the modified commands

### Post-release steps

Merge [documentation PR](https://github.com/Shopify/shopify-dev/pull/34833)

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible [documentation](https://shopify.dev) changes
- [x] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Comment by Arkham** [comment]
looks good, should we also create a PR for the changes to shopify-dev?

**Comment by gonzaloriestra** [comment]
@Arkham oh, good point! I thought we were fine because it already shows `Client ID`, but we need to fix the flags themselves... I'll create another PR.

**Comment by jessehoek** [comment]
> This is great, but there are changes in the deployments-3-48 branch that reference api-key 😬 Should we do this change against that branch instead to be sure we are not missing anything? // @jessehoek
> 
> (Or do another PR there for those changes)

Good catch! Up to you folks how you want to approach this. But yes, eventually we should make sure every instance is switched from api key to client id.

**Comment by alvaro-shopify** [comment]
> This is great, but there are changes in the deployments-3-48 branch that reference api-key 😬 Should we do this change against that branch instead to be sure we are not missing anything? // @jessehoek
> 
> (Or do another PR there for those changes)

@isaacroldan @gonzaloriestra @jessehoek  [there are plans ](https://shopify.slack.com/archives/C03NT4BP8N9/p1687323015908299) to merge `deployments-3-48` to `main` really soon. IMO I will create this PR against that branch 
- avoid merging conflicts on that `branch`.
- switch to `client ID` in all the additional mentions to `API key` in that branch

**Comment by Arkham** [comment]
Okie, I'll go ahead and merge this to `main`, and we can deal with the merge conflicts later :)

**Review by Arkham — APPROVED** [review]

**Pull request merged**
