### PR TITLE
Fix typo in the checkout-cart-url flag description

### PR DESCRIPTION
**Pull request by indigolain**
### WHAT is this pull request doing?
A minor typo fix in the CLI description for the checkout-cart-url flag.

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible [documentation](https://shopify.dev) changes
- [x] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Comment by indigolain** [comment]
signed

**Review by Arkham — APPROVED** [review]
Thanks!

**Comment by Arkham** [comment]
hey @indigolain, could you run `pnpm refresh-manifests` and push the changes? 🙇

**Comment by indigolain** [comment]
@Arkham 
Ran `pnpm refresh-manifests` and the CI seems to be passing! Thank you!

**Comment by Arkham** [comment]
merged, thank you for the fix :)

**Pull request merged**
