### PR TITLE
Fix development and live flag documentation for open theme open command

### PR DESCRIPTION
**Pull request by jeffreyguenther**
### WHY are these changes introduced?

These docs look to be from a different command. Let's change them to a version based on the docs live on shopify.dev

### WHAT is this pull request doing?

Fixes docs for:
* `shopify theme open -d`
* `shopify theme open -l`

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible [documentation](https://shopify.dev) changes
- [x] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Review by isaacroldan — APPROVED** [review]

**Review by karreiro — APPROVED** [review]

**Comment by isaacroldan** [comment]
Hi @jeffreyguenther ! Thank you for your contribution :)
You'd need to run `pnpm refresh-manifests` to update the theme command manifest with the new descriptions.
Also, please run `pnpm changeset add` to add a changelog for this fix

Thanks again!

**Comment by isaacroldan** [comment]
Hi @jeffreyguenther, sorry to bother you again. We had an issue with some of our GH actions and PRs from forks, that should be fixed now. Could you rebase again please?

**Comment by jeffreyguenther** [comment]
No problem! 

@isaacroldan after syncing with upstream main, I'm seeing this error during my rebase:

```
    ✖  nx run cli:refresh-manifests
       ›   Warning: oclif update available from 3.4.2 to 3.6.0.
           SyntaxError Plugin: @shopify/cli: The requested module '@shopify/cli-kit'
           does not provide an export named 'output'

        >  NX   ERROR: Something went wrong in run-commands - Command failed: pnpm oclif manifest

          Pass --verbose to see the stacktrace.
```

I receive this error when I run `pnpm refresh-manifests` to address the merge conflict. I ran `pnpm install` to make sure I have latest packages. Seems there's something going on in `cli-kit`.

**Comment by jeffreyguenther** [comment]
@isaacroldan I'm seeing this issue on `main` when running `pnpm refresh-manifest` as well.

**Comment by jeffreyguenther** [comment]
@isaacroldan Given some time has passed, should these issues be fixed with a rebase?

**Pull request closed without merging**
