### PR TITLE
Remove print extension uniqueness validation

### PR DESCRIPTION
**Pull request by alfonso-noriega**
### WHY are these changes introduced?
Remove print extension validation which should live in Core.
issue [#1183](https://github.com/orgs/Shopify/projects/7965/views/29?pane=issue&itemId=65371800#:~:text=Validation%20to%20Core-,%231183,-Edit)

**NOTE**: This shouldn't be merged until core validation is merged in this [PR](https://github.com/Shopify/shopify/pull/523523)
### WHAT is this pull request doing?

Remove the validation as it is implemented in cor in this [PR](https://github.com/Shopify/shopify/pull/523523)

### How to test your changes?
- Create an app with two print extensions with the same target
- In the CLI project, checkout the branch `1183-move-cli-validation-to-core`
- In an spin instance, go to shopify shell and  checkout the branch `1183-move-cli-validation-to-core`
- Try to deploy the app using the local CLI branch, it should return an error mensioning the extension handles and the target

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible [documentation](https://shopify.dev) changes

### CODE REVIEW

**Review by vividviolet — COMMENTED** [review]
I'm good with removing the validation but it would mean they can still `dev` an app with duplicated print targets even if the backend validation fails. Should we actually be failing the `dev` process when an error happens when attempting to update the draft version?

cc @isaacroldan

**Comment by alfonso-noriega** [comment]
> ...it would mean they can still dev an app with duplicated print targets even if the backend validation fails. Should we actually be failing the dev process when an error happens when attempting to update the extension version?...

@vividviolet,`dev` fails also in with the core validation. as the `draft_version` is persisted and goes through the app_version validation plugin.

**Comment by alfonso-noriega** [comment]
> ...it would mean they can still dev an app with duplicated print targets even if the backend validation fails. Should we actually be failing the dev process when an error happens when attempting to update the extension version?...

@vividviolet,this won't be an issue anymore once the new consistent dev and dev dashboard projects land as they will create a version on `dev`?

**Comment by isaacroldan** [comment]
>  What I'm suggesting is for us to just fail on validation errors instead of letting them go through with dev using a "broken" extension.

I think it makes sense to stop `dev` if there is an error in the draft upload.

**Pull request closed without merging**
