### PR TITLE
Build and dev extensions by default using the new Node logic

### PR DESCRIPTION
**Pull request by pepicrft**
### WHY are these changes introduced?
After testing the new Node logic for building and deving extensions and fixing some bugs that emerged (), we are in a position to make it the default in the next release and give users the options to opt-back into the Go logic if they encounter issues.

### WHAT is this pull request doing?
I'm making the new Node logic the default and giving users the option to use the Go workflow by passing the environment variable `SHOPIFY_CLI_USE_GO_BINARY=1`. If no major issues arise, we'll remove the Go logic after two weeks.

### How to test your changes?
You should be able to `build` and `dev` the fixture app.

### Approval from teams developing extension types

This is a significant change so it's important that we feel confident across the board before merging it. If you are part of a team that maintains an extension type, please, tophat the new workflow and confirm that everything works as expected. Please, make sure you test `build` and `dev` and scenarios other than the happy path (e.g. hot reloading, hiding/showing the extension, navigating to the extension surface):

| Extension type | Reviewer | Approved |
| ---- | ---- | --- |
|  Post-purchase UI | @carolinesalib  | 🟢|
|  Web pixel | @sandor-shopify | 🟢 |
| Checkout UI | @jamesvidler | 🟢  |
| Subscription UI | @vividviolet  | 🟢 |
| Customer accounts UI | @TobiasBales  / @robin-drexler |🟢 |
| POS UI  | @samiulmonir06  | 🟢  |

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible [documentation](https://shopify.dev) changes
- [x] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Review by jamesvidler — COMMENTED** [review]
**Tested the following cases for Checkout UI Extensions, with no error:** 👍 
- Renders a simple local checkout ui extension
- Renders a local checkout ui extension with the network_access capability
- Renders a local checkout ui extension with the block_progress capability
- Renders a local checkout ui extension with merchant configuration (i.e. settings)
- Renders a local checkout ui extension that can read metafields
- Hot-reloading with code and locale files
- Deploy extensions and verify persisted extensions render 


I did find one potential issue though 🐛 . It has to do with `approvalScopes` not being returned.

For example, the HTTP response from the `/extensions` local endpoint from the **GO CLI** is:
```
{
  "app": { "apiKey": "83a7b85991ea4e83b75ae3535eb6a8f2" },
  "version": "3",
  "root": {
    "url": "https://625b-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions"
  },
  "socket": {
    "url": "wss://625b-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions"
  },
  "devConsole": {
    "url": "https://625b-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions/dev-console"
  },
  "store": "james-prod-dev-store.myshopify.com",
  "extensions": [
    {
      "assets": {
        "main": {
          "name": "main",
          "url": "https://625b-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions/8fd932c0-7cd4-4b1b-8c67-1446d61d1722/assets/main.js",
          "lastUpdated": 1665512546
        }
      },
      "capabilities": { "networkAccess": true, "blockProgress": false },
      "development": {
        "resource": { "url": "/cart/42183785709590:1" },
        "root": {
          "url": "https://625b-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions/8fd932c0-7cd4-4b1b-8c67-1446d61d1722"
        },
        "hidden": false,
        "status": "success",
        "localizationStatus": "success"
      },
      "extensionPoints": ["Checkout::Dynamic::Render"],
      "localization": {
        "defaultLocale": "en",
        "translations": {
          "en": { "welcome": "Welcome to the {{extensionPoint}} extension!" },
          "fr": { "welcome": "Bienvenue dans l'extension {{extensionPoint}}!" }
        },
        "lastUpdated": 1665512545
      },
      "categories": null,
      "metafields": [
        { "namespace": "my-namespace", "key": "my-key" },
        { "namespace": "my-namespace", "key": "my-key-2" }
      ],
      "type": "checkout_ui_extension",
      "externalType": "checkout_ui",
      "uuid": "8fd932c0-7cd4-4b1b-8c67-1446d61d1722",
      "version": "0.20.0",
      "surface": "checkout",
      "title": "network_access_tophat",
      "approvalScopes": ["read_checkout_external_data"]
    },
    {
      "assets": {
        "main": {
          "name": "main",
          "url": "https://625b-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions/2d83b883-0dc8-4359-a8ff-72fb805a6e09/assets/main.js",
          "lastUpdated": 1665512546
        }
      },
      "capabilities": { "networkAccess": false, "blockProgress": false },
      "development": {
        "resource": { "url": "/cart/42183785709590:1" },
        "root": {
          "url": "https://625b-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions/2d83b883-0dc8-4359-a8ff-72fb805a6e09"
        },
        "hidden": false,
        "status": "success",
        "localizationStatus": "success"
      },
      "extensionPoints": [
        "Checkout::Dynamic::Render",
        "Checkout::Contact::RenderAfter"
      ],
      "localization": {
        "defaultLocale": "en",
        "translations": {
          "en": { "welcome": "Welcome to my {{extensionPoint}} extension!" },
          "fr": { "welcome": "Bienvenue dans l'extension {{extensionPoint}}!" }
        },
        "lastUpdated": 1665512545
      },
      "categories": null,
      "metafields": null,
      "type": "checkout_ui_extension",
      "externalType": "checkout_ui",
      "uuid": "2d83b883-0dc8-4359-a8ff-72fb805a6e09",
      "version": "0.20.0",
      "surface": "checkout",
      "title": "synergistic-vertical-ext",
      "approvalScopes": ["read_checkout_external_data"]
    }
  ]
}
```

Whereas the HTTP response from `/extensions` local endpoint from the **Node CLI** is:
```
Node
{
  "app": { "apiKey": "83a7b85991ea4e83b75ae3535eb6a8f2" },
  "version": "3",
  "root": {
    "url": "https://6b29-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions"
  },
  "socket": {
    "url": "wss://6b29-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions"
  },
  "devConsole": {
    "url": "https://6b29-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions/dev-console"
  },
  "store": "james-prod-dev-store.myshopify.com",
  "extensions": [
    {
      "assets": {
        "main": {
          "name": "main",
          "url": "https://6b29-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions/8fd932c0-7cd4-4b1b-8c67-1446d61d1722/assets/main.js",
          "lastUpdated": 1665511187275
        }
      },
      "capabilities": { "blockProgress": false, "networkAccess": true },
      "development": {
        "resource": { "url": "/cart/42183785709590:1" },
        "root": {
          "url": "https://6b29-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions/8fd932c0-7cd4-4b1b-8c67-1446d61d1722"
        },
        "hidden": false,
        "localizationStatus": "success",
        "status": "success"
      },
      "extensionPoints": ["Checkout::Dynamic::Render"],
      "localization": {
        "defaultLocale": "en",
        "translations": {
          "en": { "welcome": "Welcome to the {{extensionPoint}} extension!" },
          "fr": { "welcome": "Bienvenue dans l'extension {{extensionPoint}}!" }
        },
        "lastUpdated": 1665512230431
      },
      "categories": null,
      "metafields": [
        { "namespace": "my-namespace", "key": "my-key" },
        { "namespace": "my-namespace", "key": "my-key-2" }
      ],
      "type": "checkout_ui_extension",
      "externalType": "checkout_ui",
      "uuid": "8fd932c0-7cd4-4b1b-8c67-1446d61d1722",
      "surface": "checkout",
      "version": "0.20.0",
      "title": "network_access_tophat"
    },
    {
      "assets": {
        "main": {
          "name": "main",
          "url": "https://6b29-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions/2d83b883-0dc8-4359-a8ff-72fb805a6e09/assets/main.js",
          "lastUpdated": 1665511067319
        }
      },
      "capabilities": { "blockProgress": false, "networkAccess": false },
      "development": {
        "resource": { "url": "/cart/42183785709590:1" },
        "root": {
          "url": "https://6b29-2607-fea8-7df-c2f0-2de0-d402-ce8f-2c20.ngrok.io/extensions/2d83b883-0dc8-4359-a8ff-72fb805a6e09"
        },
        "hidden": false,
        "localizationStatus": "success",
        "status": "success"
      },
      "extensionPoints": [
        "Checkout::Dynamic::Render",
        "Checkout::Contact::RenderAfter"
      ],
      "localization": {
        "defaultLocale": "en",
        "translations": {
          "fr": { "welcome": "Bienvenue dans l'extension {{extensionPoint}}!" },
          "en": { "welcome": "Welcome to my {{extensionPoint}} extension!" }
        },
        "lastUpdated": 1665512230432
      },
      "categories": null,
      "metafields": null,
      "type": "checkout_ui_extension",
      "externalType": "checkout_ui",
      "uuid": "2d83b883-0dc8-4359-a8ff-72fb805a6e09",
      "surface": "checkout",
      "version": "0.20.0",
      "title": "synergistic-vertical-ext"
    }
  ]
}
```
The **Node CLI** is missing the `approvalScopes` property. I'm not entirely sure what negative impacts this has, but I know `approvalScopes` are used for gating `network_access` and  protecting customer PII.

**Comment by pepicrft** [comment]
Thanks @jamesvidler and @vividviolet for helping with the tophatting. I'm looking into the issues that you reported.

**Comment by pepicrft** [comment]
@jamesvidler I pushed a [commit](https://github.com/Shopify/cli/pull/616/commits/8dd7e36d6aab0dc1a22dff139f7bfa39f84da7d5) fixing the issue you reported. We were not including that attribute in the payload that we generate.

**Review by vividviolet — COMMENTED** [review]
I can confirm that the issue with Product Subscription was unrelated - I had to create a new app because the deploy for Post Purchase failed and then I forgot to install the new app so the extension did not show up.

Testing the extension through the QR code seems to be broken now but I need to confirm if this issue also happens on the Go code or not. 
image

**Comment by vividviolet** [comment]
@byrichardpowell are you actually able to open the extension? We need to validate that it actually renders. Can you look for Purchase Options and then select Add/Create to see if the extension shows up as a selection?

**Comment by byrichardpowell** [comment]
@vividviolet  yep it works:

Screen Shot 2022-10-17 at 4 42 25 PM

Marking as green.

**Review by sandor-shopify — APPROVED** [review]

**Comment by byrichardpowell** [comment]
@sandor-shopify kindly paired with me on this and I learnt a lot about web pixels as a result.  TLDR; This is good on the web pixel front.

**Review by jamesvidler — APPROVED** [review]

**Review by carolinesalib — APPROVED** [review]

**Pull request merged**
