### PR TITLE
Bump Shopify/theme-tools packages

### PR DESCRIPTION
**Pull request by charlespwd**
Bump theme tools dependencies

### How to test your changes?

https://github.com/user-attachments/assets/d2f01ff7-cbb7-4352-916a-45077827def9

#### theme check

```sh
pnpm build
pnpm shopify:run theme check --path=../dawn
```

#### language server

0. Build the project

  ```sh
  pnpm build
  ```

2. Create a globally accessible `liquid-language-server` command. Mine is in `$HOME/bin`

  `.zshrc`
  ```sh
  export PATH="$HOME/bin:$PATH"
  ```
  
  `$HOME/bin/liquid-language-server`
  ```
  #!/usr/bin/env bash
  cd $HOME/src/github.com/Shopify/cli
  pnpm run --silent shopify:run theme language-server
  ```

3. install neovim
4. setup https://github.com/neoclide/coc.nvim & https://github.com/tpope/vim-liquid
5. `:CocConfig`
6. Add the following config

  ```json
  {
    "languageserver": {
      "theme-check": {
        "command": "liquid-language-server",
        "trace.server": "verbose",
        "filetypes": ["liquid", "liquid.html"],
        "rootPatterns": [".theme-check.yml", "snippets/*"],
        "settings": {
          "themeCheck": {
            "checkOnSave": true,
            "checkOnEnter": true,
            "checkOnChange": false
          }
        }
      }
    },
  }
  ```

Go to a liquid repo, fire up the editor and see completions/linting/etc running fine.

### CODE REVIEW

**Comment by jamesmengo** [comment]
Some weird formatting seems to be breaking tests here - lmk if you need some help looking into it

**Comment by charlespwd** [comment]
oh I forgot about this pr. yeah it's a windows-paths-in-tests expectation issue. gotta fix that

**Comment by charlespwd** [comment]
@jamesmengo should be good to go now!

**Review by gonzaloriestra — APPROVED** [review]

**Comment by charlespwd** [comment]
Well CI did its job and caught a type-check error that would happen only after merge 👍

**Pull request merged**
