### PR TITLE
Split kitchen sink

### PR DESCRIPTION
**Pull request by matteodepalo**
### WHY are these changes introduced?

The `kitchen-sink` command was starting to become too big.

### WHAT is this pull request doing?

I've split the command into three subcomands:
- `prompts` displays just prompts such as selects and text inputs
- `banners` displays only the banner components
- `async` displays the two components that deal with async tasks: `Tasks` and `ConcurrentOutput`.

### How to test your changes?

- Run `shopify kitchen-sink all` to see the previous behavior
- Run `shopify kitchen-sink prompts` to see just prompts
- Run `shopify kitchen-sink banners` to see just banners
- Run `shopify kitchen-sink async` to see just async stuff

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible [documentation](https://shopify.dev) changes
- [x] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Review by isaacroldan — APPROVED** [review]

**Comment by matteodepalo** [comment]
Actually about the first point, I found a way to hide the topic but not the subcommands so you can run `pnpm shopify kitchen-sink --help` and get a full list of commands.

**Comment by matteodepalo** [comment]
>Good idea! Is there any quick way to do this with a topic? I tried looking in the oclif docs but I didn't find anything related to this. Maybe a index.ts command?

I found that I can do `index.ts` and use `aliases = ['kitchen-sink all']` to achieve this.

**Comment by gonzaloriestra** [comment]
Regarding the default option, I don't know if there is an easier way, but we could achieve it by using flags instead of subcommands, like `kitchen-sink`, `kitchen-sink --prompts`...

About the name, it's probably my problem because I know is a common term, but I always have problems to remember it 😅

**Review by gonzaloriestra — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
