### PR TITLE
Use cli as a dependency of app, forwarding the command

### PR DESCRIPTION
**Pull request by amcaplan**
### WHY are these changes introduced?

Users often get confused on upgrades, and don't upgrade both `@shopify/cli` and `@shopify/app`.

### WHAT is this pull request doing?

Reduces Shopify CLI to 1 single dependency, `@shopify/app`. This means the CLI gets updated atomically.

Next steps will be:

1. Update templates to remove the extra dependency
1. Decide whether to offer to auto-migrate users (since they can now drop the `@shopify/cli` dependency).

### How to test your changes?

Use `npm init` to create a new app. Point `@shopify/app` to the local copy, and delete the `@shopify/cli` dependency. Everything should still work as usual.

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible [documentation](https://shopify.dev) changes
- [x] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Review by alvaro-shopify — APPROVED** [review]
Great job!

I guess we should also need to update the `create-app` and `upgrade` commands as well

**Comment by amcaplan** [comment]
Updating to Draft for now, as I see this will be controversial.

**Comment by shauns** [comment]
Lets keep this open. Hopefully to be visited soon.

**Comment by amcaplan** [comment]
Leave it open. It'll probably be easier to redo vs. solving all the merge conflicts, but this is a good automatic  reminder.

**Comment by alvaro-shopify** [comment]
is [this](https://github.com/Shopify/cli/blob/9aca10a72e2a322e5621c6f28e2b8e52ce58344a/packages/cli/package.json#L29) still be needed?, I think that each package that includes the `cli` should "install" its own `shopify binary` right?

**Comment by amcaplan** [comment]
@alvaro-shopify I only dealt with the `app` package, but the binstub still necessary for themes and h2, unless we perform the same change there.

**Pull request closed without merging**
