### PR TITLE
Add `--message` and `--version` flags to the `app deploy` command

### PR DESCRIPTION
**Pull request by AniTumany**
### WHY are these changes introduced?

Closes https://github.com/Shopify/develop-app-foundations/issues/314

### Measuring impact

How do we know this change was effective? Please choose one:

- [ ] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible [documentation](https://shopify.dev) changes
- [ ] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Comment by ani-shopify** [comment]
Still need to work on adding unit tests

**Review by mattnoakes — COMMENTED** [review]
Looks good, Ani! Tophatting worked as expected when running `app deploy` with and without the `message` and `version` flags for an app with deployments enabled. However, when I run `app deploy` with the `message` flag (the `version` flag works) for an app with deployments disabled, I get this error:
29-51-ybv3y-0t7hs
Is it okay to error out in this case?

**Comment by ani-shopify** [comment]
> However, when I run app deploy with the message flag (the version flag works) for an app with deployments disabled, I get this error:
image
Is it okay to error out in this case?


I looked at this briefly. The issue is that [the `Apps::Models::Deployments::CreateStub` operation gets a `message` argument which it doesn't expect](https://github.com/Shopify/shopify/blob/9ef4325587b101a9bd05115cfa3e2bb70c5916ac/components/apps/app/controllers/services/internal/deployments_controller.rb#L229). 

image

Which we can easily fix in the backend. But I wonder if we should expect Shopify Core to handle these exceptions and not blow on user's face. @gordonhirsch what are your thoughts?

**Review by mattnoakes — APPROVED** [review]
> what do you think about merging this in and fix that bug on the backend separately?

Sounds good! This looks great!

**Pull request merged**
