### PR TITLE
Fix: Handle localized URLs in storefront password validation

### PR DESCRIPTION
**Pull request by AaronBarcos**
### WHY are these changes introduced?

Possible Issue Fixes: #4912 

The function `isStorefrontPasswordCorrect` fails to validate the store password when the store redirects to a localized URL, such as `https://example.myshopify.com/en`. This happens because the current implementation only expects the base store URL without any additional paths. As a result, users with stores configured for multiple languages are unable to authenticate properly, leading to incorrect password validation and repeated prompts for the password.

### WHAT is this pull request doing?

This pull request modifies the `isStorefrontPasswordCorrect` function to handle localized URLs correctly. It replaces the strict regular expression validation with a more robust approach using the `URL` object to compare the origins of the redirected URL and the store URL. By resolving the redirected URL relative to the store URL and comparing their origins, we ensure that any redirection to the same store domain, regardless of the path or locale, is considered valid. This change also includes proper error handling for cases where the `location` header might be missing or invalid.

### How to test your changes?

1.  Unit Tests:

- Run the updated unit tests to ensure that the function behaves correctly with localized URLs and other edge cases.

```
pnpm test packages/theme
``` 

- Verify that all tests pass, including the new tests covering localized URL redirections.

2.  Manual Testing:

- Set up a Shopify store with multiple languages enabled.
- Use the local version of the Shopify CLI to run:

```
pnpm shopify theme dev
``` 

- When prompted for the password, enter the correct store password.
- Confirm that the CLI accepts the password and proceeds without further prompts.
- Repeat the process with an incorrect password to ensure that invalid passwords are still handled appropriately.

### Post-release steps

It would be worth checking why the localised redirect is returned. It is unclear whether this is API or backend related. Investigating this behaviour could help identify whether additional adjustments are required in the CLI or whether there are underlying issues that need to be addressed elsewhere in the system.

### Measuring impact

How do we know this change was effective? Please choose one:

- [ ] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible [documentation](https://shopify.dev) changes

### CODE REVIEW

**Comment by AaronBarcos** [comment]
@jamesmengo 

Hey! Thanks for the reply

Here is the verbose logs:

```
 NX   Successfully ran target build for project cli and 10 tasks it depends on (299ms)

Nx read the output from the cache instead of running the command for 11 out of 11 tasks.

2024-11-26T08:58:26.695Z: Running command theme dev
2024-11-26T08:58:26.699Z: Notifications to show: 0
2024-11-26T08:58:26.708Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2024-11-26T08:58:26.708Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store test-store.myshopify.com:
[]

2024-11-26T08:58:26.708Z: Getting session store...
2024-11-26T08:58:26.708Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "test-store.myshopify.com"
  }
}

2024-11-26T08:58:26.708Z: Initiating the full authentication flow...
2024-11-26T08:58:26.709Z: Requesting device authorization code...
2024-11-26T08:58:26.709Z: Sending POST request to URL https://accounts.shopify.com/oauth/device_authorization
With request headers:
 - User-Agent: Shopify CLI; v=3.70.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json
 - Content-type: application/x-www-form-urlencoded

2024-11-26T08:58:26.961Z: Request to https://accounts.shopify.com/oauth/device_authorization completed in 252 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"cb142c5b5a0647e072545aadab8961ee"
 - server-timing: processing;dur=60, socket_queue;dur=1.844, edge;dur=1.013, util;dur=0.0, cfRequestDuration;dur=194.999933
 - x-request-id: 95b0338a-372d-4c06-88fa-0fdbf60aa25a-1732611506
    
2024-11-26T08:58:26.966Z: Received device authorization code: {
  "verification_uri": "https://shopify.com/activate",
  "verification_uri_complete": "https://accounts.shopify.com/activate-with-code?device_code%5Buser_code%5D=ZPLP-JRQC",
  "expires_in": 599,
  "interval": 5,
  "device_code": "727358dc-5f77-4c0d-9962-273e7cbb52de",
  "user_code": "ZPLP-JRQC"
}

To run this command, log in to Shopify.
User verification code: ZPLP-JRQC
👉 Press any key to open the login page on your browser
Opened link to start the auth process: https://accounts.shopify.com/activate-with-code?device_code%5Buser_code%5D=ZPLP-JRQC
2024-11-26T08:58:29.984Z: Starting polling for the identity token...
2024-11-26T08:58:34.988Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=727358dc-5f77-4c0d-9962-273e7cbb52de&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.70.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-11-26T08:58:35.185Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=727358dc-5f77-4c0d-9962-273e7cbb52de&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 195 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - server-timing: processing;dur=15, socket_queue;dur=1.595, edge;dur=1.016, util;dur=0.0, cfRequestDuration;dur=145.999908
 - x-request-id: 13455934-b2ee-4907-93f0-ffc9b048ba95-1732611515
    
2024-11-26T08:58:35.185Z: Polling for device authorization... status: authorization_pending
2024-11-26T08:58:40.188Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=727358dc-5f77-4c0d-9962-273e7cbb52de&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.70.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-11-26T08:58:40.384Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=727358dc-5f77-4c0d-9962-273e7cbb52de&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 196 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - server-timing: processing;dur=14, socket_queue;dur=1.995, edge;dur=1.015, util;dur=0.05, cfRequestDuration;dur=151.999712
 - x-request-id: 68038255-3be2-4560-acd0-8d3b528bbcbc-1732611520
    
2024-11-26T08:58:40.384Z: Polling for device authorization... status: authorization_pending
2024-11-26T08:58:45.386Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=727358dc-5f77-4c0d-9962-273e7cbb52de&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.70.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-11-26T08:58:45.656Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=727358dc-5f77-4c0d-9962-273e7cbb52de&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 270 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"a654c046d57d84cae5fcf64d3477d513"
 - server-timing: processing;dur=102, socket_queue;dur=1.661, edge;dur=1.02, util;dur=0.05, cfRequestDuration;dur=224.999905
 - x-request-id: 83ac9362-dd91-4e21-b63a-d5060c2c2ce9-1732611525
    
2024-11-26T08:58:45.660Z: CLI token received. Exchanging it for application tokens...
2024-11-26T08:58:45.662Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.70.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-11-26T08:58:45.662Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.70.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-11-26T08:58:45.662Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.70.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-11-26T08:58:45.663Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Ftest-store.myshopify.com%2Fadmin
With request headers:
 - User-Agent: Shopify CLI; v=3.70.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-11-26T08:58:45.874Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=**** completed in 212 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"1754b5de3a82b3095a5d6adc9c61e26c"
 - server-timing: processing;dur=52, socket_queue;dur=1.095, edge;dur=2.014, util;dur=0.05, cfRequestDuration;dur=163.999796
 - x-request-id: 1b12c841-e69f-4f98-90bb-89444aea464f-1732611525
    
2024-11-26T08:58:45.878Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=**** completed in 216 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"18d8eb9a1cf57210b627da8d823087b2"
 - server-timing: processing;dur=48, socket_queue;dur=1.285, edge;dur=1.015, util;dur=0.05, cfRequestDuration;dur=174.000025
 - x-request-id: ba3d305f-83f3-462b-9acf-9145386fe1c3-1732611525
    
2024-11-26T08:58:45.882Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=**** completed in 220 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"82983965a44266e8e61284c9c7aab399"
 - server-timing: processing;dur=49, socket_queue;dur=1.788, edge;dur=1.014, util;dur=0.0, cfRequestDuration;dur=181.999922
 - x-request-id: 33d01ee5-597e-4163-9a25-258f2a1565fd-1732611525
    
2024-11-26T08:58:46.121Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Ftest-store.myshopify.com%2Fadmin completed in 458 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"0c0a03f8674797cd6d90f8a0c593de26"
 - server-timing: processing;dur=65, socket_queue;dur=1.376, edge;dur=2.015, util;dur=0.05, cfRequestDuration;dur=409.999847
 - x-request-id: 480f67b6-a684-44f4-820c-798560235127-1732611525
    
✔ Logged in.
2024-11-26T08:58:46.125Z: Setting session store...
2024-11-26T08:58:46.132Z: Getting development theme...
2024-11-26T08:58:46.501Z: Request to https://test-store.myshopify.com/admin/api/unstable/themes/173275119953.json?fields=id%2Cname%2Crole%2Cprocessing completed in 366 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - server-timing: processing;dur=213, cfRequestDuration;dur=279.999971
 - x-request-id: f777e514-deef-4405-8de1-1b457eadda39-1732611526
    
╭─ warning ──────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                        │
│  It doesn't seem like you're running this command in a theme directory.                                │
│                                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯

?  Do you want to proceed?
✔  Yes, confirm

2024-11-26T08:58:59.411Z: Port 9292 is free
2024-11-26T08:58:59.413Z: Reading the content of file at assets/logo.png...
2024-11-26T08:58:59.565Z: Request to https://test-store.myshopify.com/ completed in 175 ms
With response headers:
 - content-type: text/html; charset=utf-8
 - server-timing: processing;dur=60, db;dur=14, db_async;dur=8.419, asn;desc="12430", edge;desc="MAD", country;desc="ES", theme;desc="174040613201", pageType;desc="index", servedBy;desc="6xlt", requestID;desc="865a6fc7-3448-4117-b6d6-24f627706b88-1732611539", cfRequestDuration;dur=119.999886
 - x-request-id: 865a6fc7-3448-4117-b6d6-24f627706b88-1732611539
    
2024-11-26T08:58:59.566Z: Getting storefront password for shop test-store.myshopify.com...
?  Enter your store password:
✔  *************

2024-11-26T08:59:16.999Z: Request to https://test-store.myshopify.com/password completed in 122 ms
With response headers:
 - content-type: text/html; charset=utf-8
 - server-timing: processing;dur=14, db;dur=7, db_async;dur=6.771, asn;desc="12430", edge;desc="MAD", country;desc="ES", pageType;desc="password", servedBy;desc="c8q8", requestID;desc="3ae19974-3157-4107-b7a2-2f6544c6e27e-1732611556", cfRequestDuration;dur=80.999851
 - x-request-id: 3ae19974-3157-4107-b7a2-2f6544c6e27e-1732611556
    
2024-11-26T08:59:17.000Z: Removing storefront password for test-store.myshopify.com...
?  Incorrect store password. Please try again:
✔  *************

2024-11-26T08:59:31.003Z: Request to https://test-store.myshopify.com/password completed in 128 ms
With response headers:
 - content-type: text/html; charset=utf-8
 - server-timing: processing;dur=10;desc="gc:1", db;dur=2, db_async;dur=1.943, asn;desc="12430", edge;desc="MAD", country;desc="ES", pageType;desc="password", servedBy;desc="2ngb", requestID;desc="b4ef2429-2697-45ff-92af-cb3f311264ee-1732611570", cfRequestDuration;dur=89.000225
 - x-request-id: b4ef2429-2697-45ff-92af-cb3f311264ee-1732611570
    
?  Incorrect store password. Please try again:
>  █
   ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔

``` 

About #4902, ignore it. It was just a confusion.

And yes, I'm still having the same problem with the official package.

**Comment by jamesmengo** [comment]
Was able to replicate + test this on my shop - worked 👍 

Thanks @AaronBarcos!

**Review by jamesmengo — APPROVED** [review]
Approving but will wait for a second set of eyes before merging

**Review by karreiro — APPROVED** [review]
Thank **you** for this PR, @AaronBarcos! 🚀 Great stuff :)

**Pull request merged**
