### PR TITLE
Cleanup ExtensionPointSpec

### PR DESCRIPTION
**Pull request by byrichardpowell**
### WHY are these changes introduced?
In the original design of extensions the CLI would have an extension point spec for each extension point. This would  allow each extensions Point to express:

 1. The redirectURL for this extension point.
 2. The previewMessage for this extension point.

We've since used an architecture where:

1. The redirectURL is logic that the extensions dev server controls and is consistent across all extension points
2. The previewMessage is constructed by the extension spec by looping through the extension points

As such, I don't see a need to keep the ExtensionPointSpec around.  This PR removes it, but the PR is intended to drive discussion.  I'm not sure this is the right move, so I'm proposing this so we can all get on the same page.

Fixes: https://github.com/Shopify/cli/issues/818

### WHAT is this pull request doing?

The commit messages have the details.

Not that this changes how plugins are registered.  I'm not sure of the consequences here, but the commit message have my thoughts.

### How to test your changes?

1. `yarn && yarn build`
2. `cd fixtures/app`
3. `yarn dev`
4. Does the app run?
5. How does this affect plugins 

### Post-release steps

None

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible [documentation](https://shopify.dev) changes
- [ ] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Comment by isaacroldan** [comment]
The original design assumed that every extension point could have a different configuration and we weren't inferring anything from the point target. It also allowed us to define new points in private plugins with specific custom configurations. (thinking on points that show different instructions or URLs even if they are for the same surface)

So, is that a real use case that could happen in the future or is it safe for now to assume that all extension points from the same surface will behave the same way? Maybe we can remove this until there is a need for it, just wanted to be sure

**Comment by byrichardpowell** [comment]
> So, is that a real use case that could happen in the future or is it safe for now to assume that all extension points from the same surface will behave the same way? Maybe we can remove this until there is a need for it, just wanted to be sure

Yeah, that's the important question.  What are your thoughts @trisha-chill ?

**Comment by lemonmade** [comment]
Hmm. There are definitely different "behaviors" per extension point — post-purchase and the soon-to-be-added order status page extension points are each deep in the flow, and we ideally want to land developers directly on them. So something needs to differentiate how to handle these extension points. But maybe that could be a responsibility of the host, and not the CLI? Like, we could make all the hosts handle some sort of protocol-based URL structure that the CLI uses for every extension point, and leave the hosts to be responsible for the logic of where to redirect to...

**Comment by vividviolet** [comment]
> But maybe that could be a responsibility of the host, and not the CLI? Like, we could make all the hosts handle some sort of protocol-based URL structure that the CLI uses for every extension point, and leave the hosts to be responsible for the logic of where to redirect to...

This is already the case for Admin extensions but not through any protocol but by the extension point/type itself.  Ex. Admin Home always redirects to the app home page after its loaded.

**Comment by byrichardpowell** [comment]
@vividviolet and I chatted about this on tuple and we are aligned with this change.

@isaacroldan  please can you review and approve the change if you are aligned? I'll rebase now.

**Pull request merged**
