### PR TITLE
Publish docs

### PR DESCRIPTION
**Pull request by amcaplan**
### WHY are these changes introduced?

We need public docs for cli-kit, so developers can explore its capabilities more easily.

### WHAT is this pull request doing?

This should expose our docs at https://shopify.github.io/cli/api/cli-kit/

1. Generate the docs in the correct directory
2. Add a top-level task to generate all the docs
3. Add doc updates to the version packages PR job (not 100% sure this will work, but it's worth a try!)
4. Add the initial docs so they're available immediately and we can confirm GH pages works as expected

### How to test your changes?

From the top level:

```sh
pnpm docs:generate
open docs/api/cli-kit/index.html
```

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible [documentation](https://shopify.dev) changes
- [x] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Comment by amcaplan** [comment]
@Arkham I didn't notice that, can you give an example?

**Comment by amcaplan** [comment]
I don't really understand the concern. All the documentation in that page is coming straight from our own code comments (see [here](https://github.com/Shopify/cli/blob/b28158523/packages/cli-kit/src/public/node/abort.ts)).

**Comment by amcaplan** [comment]
Anyway, in the interest of preventing analysis paralysis, I've dropped the external docs. Hopefully this makes it easier to give the 👍

**Review by Arkham — APPROVED** [review]
👨‍⚕️ 👩‍⚕️

**Pull request merged**
