### PR TITLE
Introduce support for the `shopify theme console` command

### PR DESCRIPTION
**Pull request by karreiro**
### WHY are these changes introduced?

This PR marks the public availability and support of the `shopify theme console` command. The beta feature warning has been removed, and several enhancements and bug fixes have been introduced.

### WHAT is this pull request doing?

Here's a summary of the changes:

* **Bug Fixes**
  * Authentication issues for users logging into non-password-protected stores have been resolved.
  * Syntax highlighting for `}` characters has been fixed.
  * Stability of the session has been improved when users include a string element.

* **New Features**
  * The `--url` flag is now supported, enabling the evaluation context to rely on a specific page.
  * Smart assignments have been introduced, allowing users to type `test = "my string"` instead of `assign test = "my string"`.

* **Improvements**
  * The password page will no longer open if the password was entered in a previous session.
  * A friendly warning will be displayed when users attempt to print objects that cannot be parsed as a JSON file (e.g., shop).
  * The session will terminate when the remote API limit is reached.

### How to test your changes?

1. Run `shopify theme console`
2. Try a Liquid object, such as `collections`
3. Try a Liquid filter, like `collections.first.handle | upcase`
4. Try a Liquid tag, for instance, `assign a = collections.first.handle | upcase`
5. Try smart assignments, like `a = 1`
6. Explore other Liquid objects

Here's a demo (notice the flag in the video is outdated, `--page` instead of `--url`):

https://github.com/Shopify/cli/assets/1079279/4c382d44-f0b2-446e-8859-c43b1e90da6a

#### Liquid Console Usage

Please note that the Liquid Console supports only single-line expressions. It automatically prints objects that implement `json` and provides a friendly message for those that do not. For more details, see [this example](https://user-images.githubusercontent.com/1079279/262913495-43f17c7c-1fac-41ba-9226-4362147fad96.png).

### Post-release steps

Update documentation.

### Measuring impact

How do we know this change was effective? Please choose one:

- [ ] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [x] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible [documentation](https://shopify.dev) changes
- [x] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Comment by mgmanzella** [comment]
might be a /nit but i was confused by this message, i didn't know if it meant i needed to log in or enter my store password (since every other command takes you to auth if you need to login)
Screenshot 2023-08-24 at 10 30 33 AM

maybe we explicitly say `Enter your store password to activate Shopify Liquid console` or something, so people aren't expecting the login page in the browser?

**Comment by karreiro** [comment]
> might be a /nit but i was confused by this message, i didn't know if it meant i needed to log in or enter my store password (since every other command takes you to auth if you need to login)
> Screenshot 2023-08-24 at 10 30 33 AM
> maybe we explicitly say `Enter your store password to activate Shopify Liquid console` or something, so people aren't expecting the login page in the browser?

This message is a bit generic, indeed. This is because some stores may not require a password, yet we still need to open the browser for authentication given our current infrastructure.

Perhaps a more precise message could be: `Activate the Shopify Liquid console in [your browser](http://localhost:9293) and enter your store password if prompted`. However, I find this version slightly verbose. What do you think about that?

**Comment by karreiro** [comment]
Thanks a lot for the review, @mgmanzella! 🚀 

Following [this comment](https://github.com/Shopify/cli/pull/2700#discussion_r1304376791), I have enhanced the error handling (here's a [demo](https://github.com/Shopify/cli/pull/2700#discussion_r1305266093)). Additionally, I've fixed a regression that occurred when I changed the flag name from `--page` to `--url`.

Please feel free to share any additional thoughts or suggestions you might have :)

**Comment by mgmanzella** [comment]
> Actually, this is expected, because we need to open the browser to authenticate at SFR. The improvement "The password page will no longer open" refers to the fact that, once users enter their password for the first time, they won't need to retype it. Instead, they will be directed straight to the success screen. Here's a https://github.com/Shopify/cli/pull/2700#discussion_r1305266093 showing that:

ah! then i misunderstood 🙏 and just so im understanding, we still have to open the browser window because we saved the password from a previous session and we're entering it ourselves vs. making the user do it again?

> Perhaps a more precise message could be: Activate the Shopify Liquid console in [your browser](http://localhost:9293/) and enter your store password if prompted. However, I personally find this version a bit verbose. Wdyt?

i like it! it is a bit verbose but i also want to avoid people opening GH issues because they misunderstand the experience, and a bit more verbose message might help prevent that

**Comment by karreiro** [comment]
> ah! then i misunderstood 🙏 and just so im understanding, we still have to open the browser window because we saved the password from a previous session and we're entering it ourselves vs. making the user do it again?

Yes, that's correct. We're relying on cookies for now, so the need to open the browser (we also, currently need to open the browser due to SFR authentication). I believe we can avoid this in the future, but it's currently necessary as we're reusing the `shopify theme dev` infrastructure.

> i like it! it is a bit verbose but i also want to avoid people opening GH issues because they misunderstand the experience, and a bit more verbose message might help prevent that

Excellent point! I've updated the message in a new commit :)

> amazing stuff 🔥 👏 tophatting looked great as well, let's ship it 🚢

Thanks a lot! Let's ship it :) 🚀

**Pull request merged**
