### PR TITLE
Accept build_directory config for theme extensions

### LINKED ISSUE #867: [Feature]: Ability to upload theme extensions from a `/dist` folder
### What area(s) will this request affect?

Extension, Deployment

### What type of change do you want to see?

Substantial change to existing feature

### Overview

A way to deploy a theme extensions (or other extensions) from a specific folder that is generated after a build command has been executed.

### Motivation

This is easily achiveable with CLI 2.x using a custom command e.g. `npm run build` (which generates a folder named `/dist`) and then running a command like `cd dist` and `shopify extension push`.

This allows us to use rollup or equivalent before the extension is pushed.

### PR DESCRIPTION
**Pull request by amcaplan**
### WHY are these changes introduced?

Fixes #867

### WHAT is this pull request doing?

Accepts a `build_directory` config in the extension config file. This can be used to have a `src`/`dist` directory setup for theme extensions.

### How to test your changes?

Move your theme files to a build directory, and configure `build_directory` in your theme app extension's TOML file. Things should work as usual.

### Post-release steps

Need to document this!

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [x] I've considered possible [documentation](https://shopify.dev) changes
- [x] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

### CODE REVIEW

**Review by shauns — COMMENTED** [review]
Looks good, worth checking with theme folks

**Comment by amcaplan** [comment]
My understanding from @karreiro's comment [here](https://github.com/Shopify/cli/issues/867#issuecomment-1340630261) is that they don't have a strong opinion about this, since it's not strictly theme-related.

**Comment by amcaplan** [comment]
Still relevant!

**Review by karreiro — COMMENTED** [review]
Thanks a lot for this PR, @amcaplan! Clean stuff 🚀  :)

Unfortunately, I've tried to 🎩 the PR and the `app dev` command hasn't worked. I believe we might need to pass the `build_directory` path to the theme app extension development server as well.

Please, let me know your thoughts and thanks again for this PR!

**Comment by shauns** [comment]
cc @amcaplan @karreiro lets try and get this one fixed

**Review by karreiro — COMMENTED** [review]
Thank you, @amcaplan! Excellent stuff 🚀 The code LGTM and it works as expected as well :)

I have only two minor questions:
1. Do we have any reason for not exposing this as a flag? It sounds like it could be useful, and if I understand things correctly, most of our TOML properties mirror CLI flags (I'm wondering if this could break users' expectations). What do you think about that? (a possible name could be `--theme-app-extension-path`, in the same vein as the `--theme-app-extension-port`)
2. Do we want to support absolute paths?

Thanks again for this PR!

**Review by karreiro — APPROVED** [review]
Thank you, @amcaplan!

**Comment by NexPB** [comment]
Just checking in if we can get some sort of action solution 👍🏻

**Pull request closed without merging**
